!!python/object:argparse.Namespace
batch_size: 128
cond_disc: false
data_path: null
downsamp_factor: 4
epochs: 30000
lambda_feat: 10
load_path: /home/ytsrt/nas189/home/stylegan2_explore/melgan-neurips/logs/final_drum_16k_melgan
log_interval: 100
n_layers_D: 4
n_mel_channels: 64
n_residual_layers: 3
n_test_samples: 8
ndf: 16
ngf: 32
num_D: 3
save_interval: 1000
save_path: logs/ISMIR_drum_retrain_melgan
seq_len: 8000
